### ISSUE TITLE
Job 触发数量过多的时候平台崩溃

### ISSUE THREAD

**Issue by YiRuiLiher** [ipfs-force-community/brightbird#123]
Job 触发数量过多的时候平台崩溃

复现方式：反复触发某个 Job

----------------------------------log----------------------------------------

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1dbd8e5]

goroutine 58 [running]:
github.com/go-git/go-git/v5.(*Repository).Worktree(...)
	/root/go_pro/pkg/mod/github.com/go-git/go-git/v5@v5.6.1/repository.go:1413
github.com/ipfs-force-community/brightbird/web/backend/job.(*DefaultImageBuilder).updateRepo(0xc001f19860, {0x2947528, 0xc000056090})
	/root/brightbird/web/backend/job/image_builder.go:303 +0x45
github.com/ipfs-force-community/brightbird/web/backend/job.(*DefaultImageBuilder).FetchCommit(0xc001f19860, {0x2947528?, 0xc000056090?}, {0xc0032d7a10, 0x28})
	/root/brightbird/web/backend/job/image_builder.go:368 +0x53
github.com/ipfs-force-community/brightbird/web/backend/job.(*BuildWorker).do(0xc000512070, {0x2947528, 0xc000056090}, 0xc000489c20)
	/root/brightbird/web/backend/job/image_builder.go:206 +0x4af
github.com/ipfs-force-community/brightbird/web/backend/job.(*BuildWorker).Start(0xc000512070, {0x2947528, 0xc000056090}, 0xc000056090?)
	/root/brightbird/web/backend/job/image_builder.go:173 +0x8f
created by github.com/ipfs-force-community/brightbird/web/backend/job.(*ImageBuilderMgr).Start
	/root/brightbird/web/backend/job/image_builder.go:147 +0x59

**Comment by hunjixin** [comment]
没复现
