### ISSUE TITLE
测试流中节点参数加载速度慢

### ISSUE THREAD

**Issue by andream7** [ipfs-force-community/brightbird#155]
点击一个节点，填参数或者修改参数时，加载参数的速度很慢。

发现点击一个节点后会请求全部节点的参数，有可能是这个原因导致的速度慢
<img width="1104" alt="image" src="https://github.com/ipfs-force-community/brightbird/assets/60541766/0296835c-4d72-43c2-8b9f-7ef6616cf5f0">

**Comment by hunjixin** [comment]
可能需要缓存一下

**Comment by andream7** [comment]
#165
