### ISSUE TITLE
venus-sector-manager 测试用例的使用存在问题

### ISSUE THREAD

**Issue by YiRuiLiher** [ipfs-force-community/brightbird#44]
<img width="1025" alt="image" src="https://github.com/ipfs-force-community/brightbird/assets/52785181/3d00003f-2040-4eb3-ba91-bf761cdd65be">

miner 的地址需要手动输入
但是此时系统还没有运行，用户并不知道矿工地址
而 add-miner 组件是知道矿工地址的，add_wallet 知道钱包地址，所以这两个都应该作为依赖参数出现

**Comment by andream7** [comment]
#53
