### ISSUE TITLE
触发任务列表页面，可以加一个触发时间的显示

### ISSUE THREAD

**Issue by YiRuiLiher** [ipfs-force-community/brightbird#68]
<img width="1712" alt="image" src="https://github.com/ipfs-force-community/brightbird/assets/52785181/a9c35d17-a7fd-476d-95c0-03ee3b42e7bc">

触发任务列表页面，可以加一个触发时间的显示，可以更迅速的查看 job 测试的时间

**Comment by hunjixin** [comment]
可以在描述下面加一项
