### ISSUE TITLE
测试插件中增加返回接口响应时间统计的结构体

### ISSUE THREAD

**Issue by YiRuiLiher** [ipfs-force-community/brightbird#91]
目前对于接口测试,比较注重接口的响应时间,我们可以加一下获取响应时间的结构体,由测试插件决定统计的时间逻辑,平台只负责接收时间并进行展示
展示方式也可以尽量简单
只是在插件测试名称的后方展示一下时间
如果可以做根据时间进行排序更好

![image](https://github.com/ipfs-force-community/brightbird/assets/52785181/42870e28-7317-454b-8821-d75bd859e00b)

**Comment by hunjixin** [comment]
插件自己写

**Comment by hunjixin** [comment]
没有意义，一次两次快慢也说明不了什么。顺序是执行顺序不能动。

**Comment by YiRuiLiher** [comment]
不紧急，先关闭
