### ISSUE TITLE
为平台添加全局环境变量的设置

### ISSUE THREAD

**Issue by YiRuiLiher** [ipfs-force-community/brightbird#96]
当所有的插件都依赖于一个数值的时候，通过插件传参的方式就会比较麻烦
后端提供一个设置全局的环境变量接口，就会轻松很多

前端在 测试流编辑 和  Job  两个页面添加环境变量编辑按钮

**Comment by hunjixin** [comment]
在测试流中增加全局参数， 在job中支持给全局参数设数值。

如果测试流全局参数发生变化，job需手动相应改变。
